### ISSUE TITLE
All commands result in an error

### ISSUE THREAD

**Issue by rxi** [monolifed/theme16#2]
On the current version all the registered commands appear to result in an error when performed.

**Comment by monolifed** [comment]
Is it on windows?
I tested it on linux with the latest git version and it worked

**Comment by rxi** [comment]
On linux. I probably should have clarified: this is when no other functions from the module have been called, in contrast to the example in the README

**Comment by monolifed** [comment]
9c97c69 does it fix it?

**Comment by rxi** [comment]
That looks like it requires `M.apply` to be called before the commands are even registered and would re-register the commands each time `M.apply` is called. The previous behaviour allowed you to not call `M.apply` (or any other function) but bind the `next` and `prev` commands to hotkeys, such that you could preview the themes quickly to find one you liked without setting an initial one.

**Comment by monolifed** [comment]
I understand the problem now.
Also I didn't notice that files in plugins directory were automatically required.

**Comment by monolifed** [comment]
Can I use config to set/get variables (for example user sets config.theme_uselistfile)? Using module itself then calling apply doesn't seem to be a good way.

**Comment by rxi** [comment]
Yep, [this is supported](https://github.com/rxi/lite-plugins/blob/master/plugins/spellcheck.lua#L9) -- note though, that the plugins are loaded *before* the `user/init.lua` file which would be where custom config values are set. Typically this means that the result of using a config variable should not be cached, but if you're feeling lazy and don't expect the config value to change at runtime, the `core.add_thread()` function can be used to simply defer a function to *after* the `user/init.lua` file has been loaded -- this is what the `spellcheck` plugin does.

**Comment by monolifed** [comment]
I ended up doing some other changes too. I hope this is fixed now

**Comment by rxi** [comment]
All seems to be working for me. Thanks!
